services:
  postgres:
    image: postgres:16
    container_name: sm_postgres
    environment:
      POSTGRES_DB: studentmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

backend:
  build: ./backend/student-manager
  ports:
    - "5030:5030"
  depends_on:
    - postgres
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studentmanager

frontend:
  build: ./frontend
  ports:
    - "80:80"
  depends_on:
    - backend

volumes:
  postgres_data:
