-- Baseline: the schema Hibernate ddl-auto=update had built up to the point Flyway was
-- introduced (includes registration_invites, dropped again in V2). Databases that
-- already have this schema skip V1 via baseline-on-migrate; fresh databases run it.


CREATE TABLE public.courses (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    code character varying(255) NOT NULL,
    credit_hours integer NOT NULL,
    description character varying(255),
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    teacher_id bigint,
    term_id bigint,
    created_by character varying(255),
    updated_by character varying(255),
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT courses_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'ARCHIVED'::character varying])::text[])))
);

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.enrollments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    enrolled_at date NOT NULL,
    grade character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT enrollments_grade_check CHECK (((grade)::text = ANY ((ARRAY['A'::character varying, 'B'::character varying, 'C'::character varying, 'D'::character varying, 'F'::character varying, 'NOT_GRADED'::character varying])::text[]))),
    CONSTRAINT enrollments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.enrollments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrollments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.registration_invites (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    code character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    role character varying(255) NOT NULL,
    target_id bigint NOT NULL,
    target_type character varying(255) NOT NULL,
    used_at timestamp(6) without time zone,
    issued_by bigint,
    created_by character varying(255),
    updated_by character varying(255),
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT registration_invites_role_check CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'TEACHER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT registration_invites_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['STUDENT'::character varying, 'TEACHER'::character varying])::text[])))
);

ALTER TABLE public.registration_invites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registration_invites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.students (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    birth_date date,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    matriculation_number character varying(255) NOT NULL,
    user_id bigint,
    created_by character varying(255),
    updated_by character varying(255),
    version bigint DEFAULT 0 NOT NULL
);

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.teachers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    department character varying(255),
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    user_id bigint,
    created_by character varying(255),
    updated_by character varying(255),
    version bigint DEFAULT 0 NOT NULL
);

ALTER TABLE public.teachers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teachers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.terms (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    end_date date,
    name character varying(255) NOT NULL,
    start_date date,
    created_by character varying(255),
    updated_by character varying(255),
    version bigint DEFAULT 0 NOT NULL
);

ALTER TABLE public.terms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255),
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'TEACHER'::character varying, 'ADMIN'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT enrollments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.registration_invites
    ADD CONSTRAINT registration_invites_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.terms
    ADD CONSTRAINT terms_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.registration_invites
    ADD CONSTRAINT uk2umvykved8vlko9melwrhgnl7 UNIQUE (code);

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT uk4l9jjfvsct1dd5aufnurxcvbs UNIQUE (email);

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT uk61og8rbqdd2y28rx2et5fdnxd UNIQUE (code);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT ukcd1k6xwg9jqtiwx9ybnxpmoh9 UNIQUE (user_id);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT uke2rndfrsx22acpq2ty1caeuyw UNIQUE (email);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT ukg4fwvutq09fjdlb4bb0byp7t UNIQUE (user_id);

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT uki0g6mfijtuh199nj653nva6j5 UNIQUE (student_id, course_id);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT uknugc4l8tvxuwtn3b2yyb1boad UNIQUE (matriculation_number);

ALTER TABLE ONLY public.terms
    ADD CONSTRAINT ukqdbo5nicw4lj82c8858ds6q76 UNIQUE (name);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk468oyt88pgk2a0cxrvxygadqg FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk51iqcgil9ojku2a8e2uop9c8n FOREIGN KEY (term_id) REFERENCES public.terms(id);

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fk8kf1u1857xgo56xbfmnif2c51 FOREIGN KEY (student_id) REFERENCES public.students(id);

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT fkb8dct7w2j1vl1r2bpstw5isc0 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkdt1cjx5ve5bdabmuuf3ibrwaq FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fkho8mcicp4196ebpltdn9wl6co FOREIGN KEY (course_id) REFERENCES public.courses(id);

ALTER TABLE ONLY public.registration_invites
    ADD CONSTRAINT fkkm4uyadqi33eoinqidy4ah53i FOREIGN KEY (issued_by) REFERENCES public.users(id);

